* Opiskelijamajoitus.net
  description of the service here
* Installation instructions for Ubuntu Server 17.04
  Follow these steps to start developing. (Ignore the $ signs – they're there just to denote the beginning of an unprivileged user's shell line.)

** System upgrade
   Make sure you're running on the latest packages
   #+BEGIN_SRC sh
   $ sudo apt-get update && sudo apt-get dist-upgrade -y
   #+END_SRC

** External dependencies
   #+BEGIN_SRC sh
   $ sudo apt-get install -y postgresql postgresql-server-dev-9.6 haskell-stack git pwgen zlib1g-dev
   #+END_SRC

** Download the webapp by cloning this repository
   #+BEGIN_SRC sh
   $ git clone https://github.com/Lasokki/omanet.git
   $ cd omanet
   #+END_SRC

** Set up variables and generate a password
   #+BEGIN_SRC sh
   $ ./initialise.py
   $ APP_PASSWORD=$(egrep password config/secret.yml | head -1 | cut -d'"' -f 2 | cut -d":" -f 3)
   $ APP_USER=$(egrep user config/secret.yml | head -1 | cut -d'"' -f 2 | cut -d":" -f 3)
   #+END_SRC

** Configuring postgresql
   Create the user and two databases
   #+BEGIN_SRC sh
   $ sudo -u postgres createuser $APP_USER
   $ sudo -u postgres psql -c "ALTER USER $APP_USER WITH PASSWORD '$APP_PASSWORD';"
   $ sudo -u postgres createdb --owner=$APP_USER omanet_dev
   $ sudo -u postgres createdb --owner=$APP_USER omanet_test
   #+END_SRC

** Stack stuff
   Get GHC and build the dependencies
   #+BEGIN_SRC sh
   $ stack build yesod-bin cabal-install --install-ghc
   #+END_SRC
   
   If the stack CDN is ultra slow, use sshuttle to proxy your https:
   #+BEGIN_SRC sh
   $ sudo apt-get install -y sshuttle
   $ sshuttle -r yourusername@an.ssh.host.you.can.connect.to 0.0.0.0/0 -vv
   #+END_SRC

   Build the libraries
   #+BEGIN_SRC sh
   $ stack build
   #+END_SRC

** Run tests
   #+BEGIN_SRC sh
   $ stack test
   #+END_SRC

** Starting the development server
   Launch the development server
   #+BEGIN_SRC sh
   $ stack exec -- yesod devel
   #+END_SRC
   The first run will do things. After it's done, press enter to rebuild.
   Then view your development site at [[http://localhost:3000/]]

** Adding a new handler
   We are building on top of the yesod [[http://www.yesodweb.com/book/scaffolding-and-the-site-template][scaffolding]]. To add a new
   handler, quite many places have to be touched. use

   #+BEGIN_SRC sh
   $ stack exec -- yesod add-handler
   #+END_SRC

   to make it easier.
   
